### ISSUE TITLE
Incorrect handling of Assembly failure

### ISSUE THREAD

**Issue by s-buchner** [transloadit/java-sdk#30] opened 2019-06-19 07:43 UTC
We are using async Assemblies.
When trying to convert the attached file to e.g. mp4 video the SDK 1.0.4 code fails at:

```
Exception in thread "pool-3-thread-1" org.json.JSONException: JSONObject["ok"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getString(JSONObject.java:717)
	at com.transloadit.sdk.response.AssemblyResponse.isAborted(AssemblyResponse.java:65)
	at com.transloadit.sdk.response.AssemblyResponse.isFinished(AssemblyResponse.java:105)
	at com.transloadit.sdk.async.AsyncAssembly.watchStatus(AsyncAssembly.java:132)
	at com.transloadit.sdk.async.AsyncAssembly$AssemblyRunnable.run(AsyncAssembly.java:239)

```
The problems is that the AssemblyProgressListener never gets called with a a result after this and code that might wait for this hangs.

[41840_1A_084S_VIDEO_TMO5_558.zip](https://github.com/transloadit/java-sdk/files/3304934/41840_1A_084S_VIDEO_TMO5_558.zip)

Example assembly. https://transloadit.com/assemblies/a283a62fcf694b8c9ef284c0188a8ee6

**Comment by ifedapoolarewaju** [comment] 2019-06-19 07:51
@s-buchner does the `onAssemblyStatusUpdateFailed` method get triggered when this error happens?

**Comment by s-buchner** [comment] 2019-06-19 07:59
Hi there,
no it does not get called - and that's the main problem for our code.

**Comment by ifedapoolarewaju** [comment] 2019-06-19 08:02
ah right, I get what the issue is now, I'll roll out a fix for this. Thank you for reporting.

**Closed** 2019-06-20 05:09 UTC
